image: jamespedwards42/alpine-gcc-make

stages:
  - build

before_script:
  - gcc -v      # Print out GCC version

compile:
  stage: build
  environment: testing
  script:
  - make
  - ./target/my-own/thread_try
  - make clean
